In [21]:
import pandas as pd
import re

# First name 작성!
first_name = 'Shon'

LLM 생성 데이터 Title - Summary - Id 연결

In [ ]:
navernews_data = pd.read_csv('../../Non_Finance_data/Naver_Stock/파일이름.csv')
navernews_data

,id,link,title,body
0,5,https://n.news.naver.com/mnews/article/277/000...,[인사] 미래에셋대우,◆신임\n\n◇ 부문대표\n\n▲ 김성락 Trading1 부문대표\n\n◇ 본부장\...
1,6,https://n.news.naver.com/mnews/article/014/000...,[인사] 미래에셋대우,◆미래에셋대우 ◇부문대표 신규 선임 △Trading1 부문대표 김성락 ◇본부장 신규...
2,8,https://n.news.naver.com/mnews/article/001/001...,"'연봉킹' 한투 차장·전무, 미래에셋대우 동반 이직",(서울=연합뉴스) 김아람 기자 = 작년 상반기에 22억원이 넘는 보수를 받아 주목받...
3,9,https://n.news.naver.com/mnews/article/015/000...,GTX·남북철도 호재 타고…건설株 달린다,"올해 증시 빛낼 테마\n(1) SOC 투자 확대\n\n정부, 부동산 공급 확대 선회..."
4,11,https://n.news.naver.com/mnews/article/015/000...,"'밑빠진 이수건설에 물 붓기'…이수화학, 사옥 팔아 자금지원",600억원 추가 유상증자\n이수건설 부실에 주가 부진\n\n[ 김익환 기자 ] 이수...
...,...,...,...,...
6550,29923,https://n.news.naver.com/mnews/article/009/000...,영풍 “고려아연 주총 효력정지를”···SMC “영풍주식 취득 적법·정당”,"경영권 분쟁 중인 영풍 측이 고려아연과 최윤범 회장, 고려아연이 100% 지배하는 ..."
6551,29928,https://n.news.naver.com/mnews/article/011/000...,믿고 계속 버텼더니 '대박'…237% 올라 '벼락부자'된 서학 개미들,아이온큐 3.9조원 규모 매입\n엔비디아·테슬라 2·3배 레버리지 투자비중 급증\n...
6552,29931,https://n.news.naver.com/mnews/article/008/000...,"엔비디아 AI 칩 수요, 정점 쳤나…PCE 물가지수 주목[오미주]",[오늘 주목되는 미국 주식시장]\nAI(인공지능) 반도체회사인 엔비디아의 주가가 마...
6553,29948,https://n.news.naver.com/mnews/article/015/000...,딥시크 쇼크에 삼전 실적 경고…K칩스株 '악몽',SK하이닉스 장중 12% 급락\n1주일 만에 개장한 국내 증시가 중국 인공지능(AI...
6554,29983,https://n.news.naver.com/mnews/article/648/000...,"[청기홍기]한화오션·현대모비스, 어닝서프라이즈에 목표가↑","한주간 증권가 목표주가 상향·하향 종목 리뷰\n한화오션, 4년만의 흑자전환...현대..."

In [ ]:
GPT_summary = pd.read_csv('../train_database/Summary.csv')
Groq_summary = pd.read_csv('../train_database/Summary_groq.csv')

Total_summary = pd.concat([GPT_summary, Groq_summary], axis=0)
index_list = Total_summary['id'].tolist()
index_naver = navernews_data['id'].tolist()


for i in index_list:
    if i not in index_naver:
        print(i)

4360
8302
29869

In [24]:
merged_data = pd.merge(Total_summary, navernews_data, on='id')
merged_data

,id,summary,link,title,body
0,1824,라임 사태가 확산되면서 알펜루트 자산운용이 2300억 원 규모의 펀드에 대한 환매 ...,https://n.news.naver.com/mnews/article/018/000...,"라임 사태 확산…알펜루트, 2300억 펀드 환매 중단 검토(종합)","- 한국투자증권 등 3개, TRS 익스포저 436억원\n- 개인투자자 투자액은 13..."
1,409,정부의 증권거래세 인하 결정에 대해 전문가들과 투자자들 사이에서 갑론을박이 벌어지고...,https://n.news.naver.com/mnews/article/029/000...,"""인하 반갑다"" VS ""안 하느니 못했다""…갑론을박","""추가인하 시기 없어 문제"" 지적\n\n""보여주기식 정책"" 개미들 반발\n\n증권거..."
2,4506,인바이오가 한국화학연구원과의 공동연구를 통해 새로운 살균제 물질에 대한 특허를 출원...,https://n.news.naver.com/mnews/article/014/000...,"인바이오, 한국화학연구원 공동연구로 신규 살균제 물질특허 출원",[파이낸셜뉴스] 친환경 작물보호제 개발∙제조 전문기업 인바이오가 한국화학연구원과 공...
3,4012,"[별별ETF] 기사에 따르면, 시장 조정기가 마무리되는 시점에서는 일반적으로 방어주...",https://n.news.naver.com/mnews/article/648/000...,[별별ETF]조정기 끝자락엔 방어주가 오른다!,통신·필수소비재 등 방어주ETF 선방\n방어주 상승 조정 후반부 진입 신호\n통신과...
4,2286,사회초년생이 결혼 자금과 부모님의 환갑 경비 등 다양한 재정적 필요성에 직면해 있어...,https://n.news.naver.com/mnews/article/014/000...,"사회초년생 ""결혼자금에 부모님 환갑 경비까지…필요한 돈 많은데 연금저축 어떻게 할까...",상품 유지하면서 재무 분배 전략 새로 세워야\nA씨(29)는 2년차 사회 초년생 직...
...,...,...,...,...,...
6561,10154,"뉴욕 증시는 장기금리 상승으로 혼조를 보였으며, 다우는 0.27% 상승했고 나스닥은...",https://n.news.naver.com/mnews/article/003/001...,"뉴욕 증시, 장기금리 상승에 혼조 출발...다우 0.27%↑ 나스닥 0.49%↓",[서울=뉴시스]이재준 기자 = 미국 뉴욕 증시는 1일 고용 관련 지표 발표를 앞두고...
6562,8269,공무원연금과 6개 정부인사급여시스템 운영기관이 합동워크숍을 개최하여 정부 인사급여시...,https://n.news.naver.com/mnews/article/018/000...,"공무원연금, 7개 정부인사급여시스템 운영기관 합동워크숍 개최",가입자관리 업무효율 제고·연금업무 프로세스 개선\n[이데일리 김성수 기자]공무원연금...
6563,10984,"중개매체펀드에서 자금을 인출한 개인 투자자들이 한국에 3300억원을 부어주었으며, ...",https://n.news.naver.com/mnews/article/009/000...,"중국펀드서 돈 뺀 중학개미들, 이 나라에는 3300억 부었다",미국 증시 오르자 수익 실현 후\n신흥국 시장으로 투자자금 유입\n탈중국 수혜국인 ...
6564,12165,"추석 연휴期间 이동객이 27% 증가했으며, 28일과 30일이 가장 붐비는 날로 예상...",https://n.news.naver.com/mnews/article/057/000...,여행 가려면 28·30일은 피하세요…'길어진' 추석연휴 이동객 27% 증가,【 앵커멘트 】\n추석 연휴가 사실상 엿새로 늘어나면서 고향 방문과 여행 등으로 연...
6565,29983,한화오션과 현대모비스가 실적超过에 따른 목표가 상승으로 주목받고 있다.,https://n.news.naver.com/mnews/article/648/000...,"[청기홍기]한화오션·현대모비스, 어닝서프라이즈에 목표가↑","한주간 증권가 목표주가 상향·하향 종목 리뷰\n한화오션, 4년만의 흑자전환...현대..."

In [28]:
email_pattern = r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
bracket_pattern = r"\[.*?\]"
reporter_pattern = r"\s*[가-힣]+\s*기자\b.*$"

merged_data['article'] = ""
Articles = []

for i in range(len(merged_data)):
    title = str(merged_data['title'][i])
    body = str(merged_data['body'][i])

    if re.search(email_pattern, body):
        body = re.split(email_pattern, body)[0]
    
    body = re.sub(bracket_pattern, '', body)
    body = re.sub(reporter_pattern, '', body, flags=re.DOTALL)
    body = body.replace('nan', '')
    
    merged_data['article'][i] = f"{title}\n{body}"

C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  merged_data['article'][i] = f"{title}\n{body}"
C:\Users\User\AppData\Local\Temp\ipykernel_9912\3869687689.py:19: SettingWithCopyWarning:

In [29]:
merged_data

,id,summary,link,title,body,article
0,1824,라임 사태가 확산되면서 알펜루트 자산운용이 2300억 원 규모의 펀드에 대한 환매 ...,https://n.news.naver.com/mnews/article/018/000...,"라임 사태 확산…알펜루트, 2300억 펀드 환매 중단 검토(종합)","- 한국투자증권 등 3개, TRS 익스포저 436억원\n- 개인투자자 투자액은 13...","라임 사태 확산…알펜루트, 2300억 펀드 환매 중단 검토(종합)\n- 한국투자증권..."
1,409,정부의 증권거래세 인하 결정에 대해 전문가들과 투자자들 사이에서 갑론을박이 벌어지고...,https://n.news.naver.com/mnews/article/029/000...,"""인하 반갑다"" VS ""안 하느니 못했다""…갑론을박","""추가인하 시기 없어 문제"" 지적\n\n""보여주기식 정책"" 개미들 반발\n\n증권거...","""인하 반갑다"" VS ""안 하느니 못했다""…갑론을박\n""추가인하 시기 없어 문제"" ..."
2,4506,인바이오가 한국화학연구원과의 공동연구를 통해 새로운 살균제 물질에 대한 특허를 출원...,https://n.news.naver.com/mnews/article/014/000...,"인바이오, 한국화학연구원 공동연구로 신규 살균제 물질특허 출원",[파이낸셜뉴스] 친환경 작물보호제 개발∙제조 전문기업 인바이오가 한국화학연구원과 공...,"인바이오, 한국화학연구원 공동연구로 신규 살균제 물질특허 출원\n 친환경 작물보호제..."
3,4012,"[별별ETF] 기사에 따르면, 시장 조정기가 마무리되는 시점에서는 일반적으로 방어주...",https://n.news.naver.com/mnews/article/648/000...,[별별ETF]조정기 끝자락엔 방어주가 오른다!,통신·필수소비재 등 방어주ETF 선방\n방어주 상승 조정 후반부 진입 신호\n통신과...,[별별ETF]조정기 끝자락엔 방어주가 오른다!\n통신·필수소비재 등 방어주ETF 선...
4,2286,사회초년생이 결혼 자금과 부모님의 환갑 경비 등 다양한 재정적 필요성에 직면해 있어...,https://n.news.naver.com/mnews/article/014/000...,"사회초년생 ""결혼자금에 부모님 환갑 경비까지…필요한 돈 많은데 연금저축 어떻게 할까...",상품 유지하면서 재무 분배 전략 새로 세워야\nA씨(29)는 2년차 사회 초년생 직...,"사회초년생 ""결혼자금에 부모님 환갑 경비까지…필요한 돈 많은데 연금저축 어떻게 할까..."
...,...,...,...,...,...,...
6561,10154,"뉴욕 증시는 장기금리 상승으로 혼조를 보였으며, 다우는 0.27% 상승했고 나스닥은...",https://n.news.naver.com/mnews/article/003/001...,"뉴욕 증시, 장기금리 상승에 혼조 출발...다우 0.27%↑ 나스닥 0.49%↓",[서울=뉴시스]이재준 기자 = 미국 뉴욕 증시는 1일 고용 관련 지표 발표를 앞두고...,"뉴욕 증시, 장기금리 상승에 혼조 출발...다우 0.27%↑ 나스닥 0.49%↓\n"
6562,8269,공무원연금과 6개 정부인사급여시스템 운영기관이 합동워크숍을 개최하여 정부 인사급여시...,https://n.news.naver.com/mnews/article/018/000...,"공무원연금, 7개 정부인사급여시스템 운영기관 합동워크숍 개최",가입자관리 업무효율 제고·연금업무 프로세스 개선\n[이데일리 김성수 기자]공무원연금...,"공무원연금, 7개 정부인사급여시스템 운영기관 합동워크숍 개최\n가입자관리 업무효율 ..."
6563,10984,"중개매체펀드에서 자금을 인출한 개인 투자자들이 한국에 3300억원을 부어주었으며, ...",https://n.news.naver.com/mnews/article/009/000...,"중국펀드서 돈 뺀 중학개미들, 이 나라에는 3300억 부었다",미국 증시 오르자 수익 실현 후\n신흥국 시장으로 투자자금 유입\n탈중국 수혜국인 ...,"중국펀드서 돈 뺀 중학개미들, 이 나라에는 3300억 부었다\n미국 증시 오르자 수..."
6564,12165,"추석 연휴期间 이동객이 27% 증가했으며, 28일과 30일이 가장 붐비는 날로 예상...",https://n.news.naver.com/mnews/article/057/000...,여행 가려면 28·30일은 피하세요…'길어진' 추석연휴 이동객 27% 증가,【 앵커멘트 】\n추석 연휴가 사실상 엿새로 늘어나면서 고향 방문과 여행 등으로 연...,여행 가려면 28·30일은 피하세요…'길어진' 추석연휴 이동객 27% 증가\n【 앵...
6565,29983,한화오션과 현대모비스가 실적超过에 따른 목표가 상승으로 주목받고 있다.,https://n.news.naver.com/mnews/article/648/000...,"[청기홍기]한화오션·현대모비스, 어닝서프라이즈에 목표가↑","한주간 증권가 목표주가 상향·하향 종목 리뷰\n한화오션, 4년만의 흑자전환...현대...","[청기홍기]한화오션·현대모비스, 어닝서프라이즈에 목표가↑\n한주간 증권가 목표주가 ..."

In [31]:
Total_summary = merged_data[['id', 'article', 'summary']]

형식: REPORT-news_s-{id} 인데, s는 본인 성 첫 글자 따서 하기로 합시다!

In [32]:
Total_summary['id'] = Total_summary['id'].apply(lambda x: f"REPORT-news_{first_name[0].lower()}-{x}")
Total_summary.head()

C:\Users\User\AppData\Local\Temp\ipykernel_9912\2395966852.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Total_summary['id'] = Total_summary['id'].apply(lambda x: f"REPORT-news_{first_name[0].lower()}-{x}")

,id,article,summary
0,REPORT-news_s-1824,"라임 사태 확산…알펜루트, 2300억 펀드 환매 중단 검토(종합)\n- 한국투자증권...",라임 사태가 확산되면서 알펜루트 자산운용이 2300억 원 규모의 펀드에 대한 환매 ...
1,REPORT-news_s-409,"""인하 반갑다"" VS ""안 하느니 못했다""…갑론을박\n""추가인하 시기 없어 문제"" ...",정부의 증권거래세 인하 결정에 대해 전문가들과 투자자들 사이에서 갑론을박이 벌어지고...
2,REPORT-news_s-4506,"인바이오, 한국화학연구원 공동연구로 신규 살균제 물질특허 출원\n 친환경 작물보호제...",인바이오가 한국화학연구원과의 공동연구를 통해 새로운 살균제 물질에 대한 특허를 출원...
3,REPORT-news_s-4012,[별별ETF]조정기 끝자락엔 방어주가 오른다!\n통신·필수소비재 등 방어주ETF 선...,"[별별ETF] 기사에 따르면, 시장 조정기가 마무리되는 시점에서는 일반적으로 방어주..."
4,REPORT-news_s-2286,"사회초년생 ""결혼자금에 부모님 환갑 경비까지…필요한 돈 많은데 연금저축 어떻게 할까...",사회초년생이 결혼 자금과 부모님의 환갑 경비 등 다양한 재정적 필요성에 직면해 있어...

In [ ]:
Total_summary.to_csv(f'../train_database/Model_dataset_{first_name[0].lower()}.csv', encoding='utf-8-sig')
print(len(Total_summary))

6566

: